name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.1.14']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python --version

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install library
        run: poetry install --no-interaction

      - name: Create .env file
        env:
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
          FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          SQLMODEL_DATABASE_URI: ${{ secrets.SQLMODEL_DATABASE_URI }}
        run: |
          touch .env
          echo PROJECT_NAME="$PROJECT_NAME" >> .env
          echo FIRST_SUPERUSER="$FIRST_SUPERUSER" >> .env
          echo FIRST_SUPERUSER_PASSWORD="$FIRST_SUPERUSER_PASSWORD" >> .env
          echo POSTGRES_DB="$POSTGRES_DB" >> .env
          echo POSTGRES_PASSWORD="$POSTGRES_PASSWORD" >> .env
          echo POSTGRES_SERVER="$POSTGRES_SERVER" >> .env
          echo POSTGRES_USER="$POSTGRES_USER" >> .env
          echo SQLMODEL_DATABASE_URI="$SQLMODEL_DATABASE_URI" >> .env
        shell: bash

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          poetry run pytest --cov=./app

      - name: Test with pytest xml
        run: |
          source .venv/bin/activate
          poetry run pytest --cov=./app --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Upload coverage reports to Codecov
        env:
          SUPER_SECRET: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t "%SUPER_SECRET%"

  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.1.14']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: poetry install

      - name: Print python versions
        run: |
          python -V
          poetry run python -V

      - name: Run black
        run: poetry run black ./app --check

      - name: Run isort
        run: poetry run isort ./app

      - name: Run flake8
        run: poetry run flake8 ./app

      - name: Run bandit
        run: poetry run bandit ./app
